[package]
name = "embed-files"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.24", features = ["derive"] }
glob = "0.3.2"
insta = "1.42.0"
regex = "1.11.1"
thiserror = "2.0.10"
